---
name: Home Assistant Configuration Check

on:
  workflow_call:
    inputs:
      version:
        description:
          "The version tag of Home Assistant to use for the configuration check."
        required: false
        type: string
      # secret-file-path:
      #   description: "The file path to the secret example file."
      #   required: false
      #   type: string
      # configuration-path:
      #   description: "The path to the Home Assistant configuration directory."
      #   required: true
      #   type: string

jobs:
  home-assistant-config-check:
    name: "Home Assistant Configuration Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Move secret example file
        run: mv ./src/config/secrets.yaml.example ./src/config/secrets.yaml

      - name: Print Home Assistant version
        uses: docker://homeassistant/home-assistant:${{ inputs.version }}
        with:
          args: python -m homeassistant --version

      - name: Check Home Assistant config
        uses: docker://homeassistant/home-assistant:${{ inputs.version }}
        with:
          args: hass --script check_config --config ./src/config
