---
name: trigger-manifest-update

on:
  workflow_call:

jobs:
  trigger-manifest-update:
    name: Trigger Kubernetes Manifest update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/theautomation/gitops/actions/workflows/update-manifest.yaml/dispatches \
            --data '{"ref": "main", "inputs": {"owner_and_repo":"${{ github.repository }}","registry":"ghcr.io","image_tag":"${{ github.sha }}"}}'
