---
name: YAML Linter

on:
  workflow_call:
    inputs:
      path:
        description:
          "The path to the directory containing YAML files that you want to
          lint."
        required: false
        type: string
        default: "."

jobs:
  yamllint:
    name: YAML Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint ${{ inputs.path }}
